# Generated by Django 5.2 on 2025-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
