# Generated by Django 5.2 on 2025-05-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('concept', 'Концепт'), ('launch', 'Запуск'), ('startup', 'Стартап'), ('implemented', 'Реализован')], default='concept', max_length=20, verbose_name='Статус проекта'),
        ),
    ]
