# Generated by Django 5.2 on 2025-05-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('concept', 'Идея'), ('launch', 'Рабочая модель'), ('ready_project', 'Готовый проект')], default='concept', max_length=20, verbose_name='Статус проекта'),
        ),
    ]
